### ISSUE TITLE
App Features

### ISSUE THREAD

**Issue by soumak77** [bottletrade/bottletrade-app#1]
Thread to discuss features to go into initial release.  Here is the current list of accepted features:
1. Add brewery to network
2. Add beer to network
3. Add winery to network
4. Add wine to network
5. Add spirit to network
6. Add distillery to network
7. Search for BWS (beer/wine/spirit) or BWD (brewery/winery/distillery) by name

**Comment by patguitar01** [comment]
1. ISO: FT (not sure if this feature is considered separate from other search feature)
2. Profile/Cyber Cellar View 
3. Inbox/Messaging
4. Trader Feed
5. Friend Requests
