### ISSUE TITLE
Release 1 - Data Management

### ISSUE THREAD

**Issue by soumak77** [bottletrade/bottletrade-app#3]
Release 1 will be centered around data management.  The following features will be part of release 1.  Features will be marked completed once final design and implementation has been approved by founders.
- [ ] Single Upload (via form)
  - [ ] Beer
  - [ ] Brewery
  - [ ] Wine
  - [ ] Winery
  - [ ] Spirit
  - [ ] Distillery
- [ ] Editing Existing
  - [ ] Beer
  - [ ] Brewery
  - [ ] Wine
  - [ ] Winery
  - [ ] Spirit
  - [ ] Distillery
- [ ] Batch Upload (via spreadsheet)
  - [ ] Beer Support
    - [ ] TSV
    - [ ] CSV
  - [ ] Brewery Support
    - [ ] TSV
    - [ ] CSV
  - [ ] Wine Support
    - [ ] TSV
    - [ ] CSV
  - [ ] Winery Support
    - [ ] TSV
    - [ ] CSV
  - [ ] Spirit Support
    - [ ] TSV
    - [ ] CSV
  - [ ] Distillery Support
    - [ ] TSV
    - [ ] CSV
- [ ] Profile Pages
  - [ ] Beer
  - [ ] Brewery
  - [ ] Wine
  - [ ] Winery
  - [ ] Spirit
  - [ ] Distillery
- [ ] Search (by name)
  - [ ] Beer Results
  - [ ] Brewery Results
  - [ ] Wine Results
  - [ ] Winery Results
  - [ ] Spirit Results
  - [ ] Distillery Results

**Comment by patguitar01** [comment]
Everything looks good to me on here. I was wondering, for the TSV/CSV uploads, are we going to leave an example of how they should best set up their databases to successfully transfer their databases onto our site? just don't know how that works exactly

**Comment by soumak77** [comment]
@zombiechuck Will be providing mockups for everything listed above, including the instructions to provide users when uploading spreadsheets.  

We will need to provide guidelines for how the spreadsheet should be formatted before uploaded.  The upload process will simply load the data into the UI, so the user will see how the data will be stored before saving.  For example I plan to show users whether the brewery/beer they have listed is in our system or if the result of uploading their spreadsheet will create a new one.  The user will then be allowed to make whatever adjustments they need to in the UI before saving the data.

**Comment by zombiechuck** [comment]
Brian is correct. I will be working on these mockups during the week. Also, should we add to the list user profiles, cyber cellar management, etc.?

**Comment by patguitar01** [comment]
Thanks Brian and Charles. 
Can we include a link (probably for desktop site) that users can download a template to use? (what if they rather fill out spreadsheet and upload as opposed to upload one by one on site?)

**Comment by soumak77** [comment]
@zombiechuck We will not be working on any other features until the above are complete.  Once the above are completed and the app is suitable for releasing to the public, we'll move onto the next release.  That is not to say this release will be public, but every release (whether internal or public) should have the same quality.  Once we've completed all features for this release, we'll figure out which features we want in the next release (likely geared around bottle trading).  Once that release is to the quality we want, we'll move onto the next release and so on and so forth.

**Comment by zombiechuck** [comment]
Got it. Thanks for clarifying Brian.

**Comment by patguitar01** [comment]
Great, thanks guys.

**Comment by soumak77** [comment]
That is not to say @zombiechuck shouldn't be working on mockups for all those features.  We should ideally have the mockups completed before we start development versus developing them along the way.

**Comment by zombiechuck** [comment]
Yes. I will be working on those mockups as well.

**Comment by zombiechuck** [comment]
Just wanted to let everyone know I have been working on mockups for the brewery and beer profile pages and I am getting pretty close to locking those in. I should be wrapping them up in the next few days and they will certainly be ready for @soumak77 and @njacalone next week.

**Comment by soumak77** [comment]
Thanks @zombiechuck.  Nick and I won't be able to work on anything this week due to the short week, but we'll pick up again Tuesday, so whatever you have by then you can send our way.

**Comment by zombiechuck** [comment]
@soumak77 - Definitely.

**Comment by zombiechuck** [comment]
Beer and Brewery Profile pages are nearly done and will be completed tonight. I am hoping to hand off these assets along with the spreadsheet mockup page for @soumak77 and @njacalone to work on tomorrow.
