### ISSUE TITLE
Spreadsheet Upload Mockup

### ISSUE THREAD

**Issue by soumak77** [bottletrade/bottletrade-app#4]
We need mockups for the process a user should go through to upload a spreadsheet.  The proposed workflow should be as follows:
1. User chooses what they want to upload.  Should be represented as a radio button with the following options:
   - Beers / Breweries / Spirits / Distilleries / Wines / Wineries
2. Once the user select what they want to upload, the user should be presented with how the spreadsheet must be constructed before uploading
3. User chooses the file they want to upload.  Uploading can support the following file types:
   - .csv
   - .tsv
4. User presses submit
   - This will run the file through the parser and populate the internal data that will be represented on the spreadsheet in the UI
5. User is presented with an editable spreadsheet they just uploaded.
   - The spreadsheet will indicate which fields are required but missing or invalid.  For instance if the field was suppose to contain ABV, but contains the value "beer", the field would be invalid and must be fixed as ABV should be a number.
   - The columns which contain the BWD name or BWS name will be styled slightly differently than the text editable fields for the other values.  If the BWD/BWS name exactly matches a single existing BWD/BWS in our system, the entry will be populated with the logo and name of the existing BWD/BWS.  If the name exactly matches multiple results, the list of results will be displayed to the user for them to choose the correct one.  If no results match, a symbol indicating the BWD/BWS will be added to the system should be displayed.
6. User updates the spreadsheet to correct any errors and ensures the BWD/BWS data is valid
7. User clicks submit which will start adding data to our system

**Comment by zombiechuck** [comment]
@soumak77 and @njacalone I will be working on the mockup for the spreadsheet import page tonight. Based on the requests above, I was planning on modeling the mockup fairly closely to what Cellar HQ's spreadsheet import feature currently supports. Please take a look at their feature here and let me know if this will work for us:

http://blog.cellarhq.com/blog/2012/04/03/csv-import-now-available/

Cheers,
Charles
