### ISSUE TITLE
Search Function on Current Site is Erroring Out

### ISSUE THREAD

**Issue by zombiechuck** [bottletrade/bottletrade-app#5]
As reported from one of our users, when performing a search on the site via Chrome, Safari and Firefox, an Error 500 page pops up. I have screenshotted it and attached it. I went ahead and tried performing a search and had the same issue on all three browsers. This means that there is currently no way for users to Search on our site. Could we make this a priority issue and have it resolved ASAP?

**Comment by zombiechuck** [comment]
Here is a screenshot of the above mentioned issue:

![screen shot 2015-07-27 at 2 00 09 pm](https://cloud.githubusercontent.com/assets/11972175/9399925/bb63c438-476f-11e5-9ca7-fd0d6c4b2714.png)

**Comment by soumak77** [comment]
@zombiechuck issues for the old web site should be entered in here: https://github.com/bottletrade/bottletrade-legacy/issues

I've moved this issue to https://github.com/bottletrade/bottletrade-legacy/issues/1

**Comment by zombiechuck** [comment]
Hi Brian,

Thanks for the info. It appears the links above are broken.

**Comment by soumak77** [comment]
I updated your access.  You should be good now.

**Comment by zombiechuck** [comment]
That appears to be working. Thanks Brian. Looking forward to getting this
issue resolved.
